APP_NAME = "Idle Slayer"
TITLE_BAR_HEIGHT = 32
SIDE_OFFSET = 8

# boost button positioning
SPRINT_BUTTON_AREA_TOP = 140
SPRINT_BUTTON_AREA_BOTTOM = 136
SPRINT_BUTTON_AREA_LEFT = 112
SPRINT_BUTTON_AREA_RIGHT = 116
SPRINT_BUTTON_CLICK_LEFT = 150
SPRINT_BUTTON_CLICK_BOTTOM = 75
